baseURL = "https://flakm.com/"
languageCode = "en"
defaultContentLanguage = "en"

copyright = "Copyright © 2023, Maciej Flak; all rights reserved."

title = "FlakM blog"
theme = "hugo-coder"
googleAnalytics = "G-3TLSQC3STQ"

paginate = 20
enableEmoji = true


[markup.highlight]
style = "github-dark"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Series"
  weight = 2
  url  = "series/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"


[params]
  author = "Maciek Flak"
  info = "Minimalist, Husband, Dad, Rust coder, Linux & FOSS enthusiast"
  description = "Simple coder blog"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"

  dateFormat = "January 2, 2006"

  favicon = "images/favicon.ico"

  colorScheme = "auto"
  hidecolorschemetoggle = false
  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  custom_css = [
    "css/main.css"
  ]

  


[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/johndoe/"

[[params.social]]
    name = "Mastodon"
    icon = "fa fa-mastodon"
    weight = 2
    url = "https://hachyderm.io/@flakm"
    rel = "me noopener"


