keys:
  - &admin_flakm DDB89AF3335111A17243467C7288322161C6A632
  - &blog_server 98a8ae1f5a1660864b2e8d253a98635a3c03a80c


creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *admin_flakm
          - *blog_server
