keys:
  - &admin_flakm DDB89AF3335111A17243467C7288322161C6A632
  - &user_amd_pc age1mhm63u49vwnkw9whperlxj6swme4vvh9w9vcu8zng8wudjplya3s4m0jq5
  - &blog_server age18y9t87xvw3lnpyecrtyddztvdwzp40x35as6xcpcwszhhw36pumqe4p9tu

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *admin_flakm
        age:
          - *user_amd_pc
          - *blog_server
