baseURL = "https://flakm.github.io/"
languageCode = "pl"
copyright = "Copyright © 2022, Maciej Flak; all rights reserved."
footnoteReturnLinkContents = "^"
title = "FlakM blog"
theme = "ananke"
enableInlineShortcodes = false
disqusShortname = "flakm-blog"
googleAnalytics = "UA-172669006-1"

pygmentsCodeFences = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"
  


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about/"
    weight = 0
#  [[menu.main]]
#    identifier = "links"
#    name = "Materiały"
#    url = "/links"
#    weight = 0    

[params]
  author = "flakm"
  description = "Simple coder blog"
  homepageImage = "/images/hello_world.jpg"
  showLanguageSwitcher = false
  share = true
  show_reading_time=true
  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  custom_css = [
    "css/main.css"
  ]


[[params.ananke_socials]]
    name = "github"
    url = "https://github.com/FlakM"



[params.prismJS]
  enable = true
  theme = "okaidia"
[params.commento]
  enable = false
  url = "https://m.commento.io"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
