baseURL = "https://flakm.github.io/"
baseurl = "https://flakm.github.io/"
languageCode = "pl"
copyright = "Copyright © 2020, Maciej Flak; all rights reserved."
footnoteReturnLinkContents = "^"
title = "FlakM blog"
theme = "ananke"
enableInlineShortcodes = false
disqusShortname = "flakm-blog"
googleAnalytics = "UA-172669006-1"

pygmentsCodeFences = true

[taxonomies]
  category = "categories"
  # series = "series"
  tag = "tags"
  author = "authors"
  


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "O mnie"
    url = "/about/"
    weight = 0

[params]
  author = "flakm"
  description = "Blog o programowaniu"
  homepageImage = "/images/hello_world.jpg"
  showLanguageSwitcher = false
  share = true
  show_reading_time=true
  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  custom_css = [
    "css/main.css"
  ]


  [params.social]
    rss = true
    email = "maciej.jan.flak@gmail.com"
    github = "https://github.com/FlakM"
    twitter="https://twitter.com/FlakMaciej"


  [params.prismJS]
    enable = true
    theme = "okaidia"
  [params.commento]
    enable = false
    url = "https://m.commento.io"