name: Checks

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Enable KVM
        run: |
          test -e /dev/kvm
          sudo chmod 666 /dev/kvm

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check project
        run: nix flake check --print-build-logs

      - name: Check static site
        run: nix flake check ./blog-static --print-build-logs
